version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/tools/html:/var/www/html
    restart: always
    networks:
      - InceptionNetwork
  mariadb:
    build: ./requirements/mariadb
    environment:
      DB_USER : ${DB_USER}
      DB_PASSWD : ${DB_PASSWD}
      DB_ROOT_PASSWD : ${DB_ROOT_PASSWD}
    container_name: mariadb
    ports:
      - "6969:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - InceptionNetwork
    

networks:
  InceptionNetwork:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/yelaissa/db
      o: bind
  wp_data:
    driver_opts:
      type: none
      device: /home/yelaissa/wp
      o: bind
