version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html/wordpress
      - adminer_data:/var/www/html/adminer
      - ./requirements/bonus/portfolio/src:/var/www/html/portfolio
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
      - portfolio
      - portainer
      - adminer
    networks:
      - InceptionNetwork
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      WP_DB_NAME : ${WP_DB_NAME}
      DB_USER : ${DB_USER}
      DB_PASSWD : ${DB_PASSWD}
      DB_ROOT_PASSWD : ${DB_ROOT_PASSWD}
    ports:
      - "6969:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - InceptionNetwork
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_USER: ${WP_USER}
      WP_PASSWD: ${WP_PASSWD}
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always
    networks:
      - InceptionNetwork
  # Bonus
  portainer:
    build: ./requirements/bonus/portainer/
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - InceptionNetwork
  portfolio:
    build: ./requirements/bonus/portfolio/
    container_name: portfolio
    restart: always
    volumes:
      - ./requirements/bonus/portfolio/src:/var/www/html/portfolio
    networks:
      - InceptionNetwork
  adminer:
    build: ./requirements/bonus/adminer/
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - adminer_data:/var/www/html/adminer
    networks:
      - InceptionNetwork

networks:
  InceptionNetwork:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      o: bind
      type: none
      device: /home/yelaissa/data/db
  wp_data:
    driver_opts:
      o: bind
      type: none
      device: /home/yelaissa/data/wp
  portainer_data:
    driver_opts:
      o: bind
      type: none
      device: /home/yelaissa/data/portainer
  adminer_data:
    driver_opts:
      o: bind
      type: none
      device: /home/yelaissa/data/adminer
