version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/tools/html:/var/www/html
    restart: always
    networks:
      - InceptionNetwork

networks:
  InceptionNetwork:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/yelaissa/db
      o: bind
  wp_data:
    driver_opts:
      type: none
      device: /home/yelaissa/wp
      o: bind